spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: mysql@1234
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  aop:
    proxy-target-class: true

  #mvc:
  #  view:
   #   prefix: /WEB-INF/Views
    #  suffix: jsp